/**
 * ── THE SINGLE ICON VOCABULARY ────────────────────────────────────────────
 *
 * Every icon shown in this portal is a **Bootstrap Icons** glyph
 * (https://icons.getbootstrap.com). The icon font is served as static CSS
 * from /public and linked in the web HTML shell, so no icon JavaScript is
 * bundled for the website.
 *
 * This module holds the app-level map + the native fallback table. It has NO
 * imports, so it can be consumed by both the web and native icon renderers
 * without dragging a platform's runtime into the other's bundle.
 */
export const APP_ICONS = {
  home: 'bi-house-door',
  homeFill: 'bi-house-door-fill',
  menu: 'bi-list',
  close: 'bi-x-lg',
  search: 'bi-search',
  download: 'bi-download',
  documentText: 'bi-file-earmark-text',
  ticket: 'bi-ticket-perforated',
  calendar: 'bi-calendar3',
  grid: 'bi-grid-3x3-gap',
  list: 'bi-list-ul',
  person: 'bi-person',
  personAdd: 'bi-person-plus',
  notifications: 'bi-bell',
  pulse: 'bi-activity',
  speedometer: 'bi-speedometer2',
  barChart: 'bi-bar-chart',
  shieldCheckmark: 'bi-shield-check',
  logOut: 'bi-box-arrow-right',
  logIn: 'bi-box-arrow-in-right',
  globe: 'bi-globe',
  location: 'bi-geo-alt',
  business: 'bi-building',
  time: 'bi-clock',
  megaphone: 'bi-megaphone',
  people: 'bi-people',
  checkmarkCircle: 'bi-check-circle',
  checkmarkDone: 'bi-check2-all',
  checkmark: 'bi-check-lg',
  closeCircle: 'bi-x-circle',
  flag: 'bi-flag',
  infoCircle: 'bi-info-circle',
  receipt: 'bi-receipt',
  warning: 'bi-exclamation-triangle',
  alertCircle: 'bi-x-circle',
  fileTray: 'bi-inbox',
  refresh: 'bi-arrow-clockwise',
  refreshCircle: 'bi-arrow-repeat',
  chevronDown: 'bi-chevron-down',
  chevronForward: 'bi-chevron-right',
  chevronLeft: 'bi-chevron-left',
  arrowForward: 'bi-arrow-right',
  archive: 'bi-archive',
  leaf: 'bi-flower1',
  map: 'bi-map',
  language: 'bi-translate',
  desktop: 'bi-display',
  eye: 'bi-eye',
  phonePortrait: 'bi-phone',
  pieChart: 'bi-pie-chart',
  clipboard: 'bi-clipboard',
  sliders: 'bi-sliders',
  filter: 'bi-funnel',
  downloadCloud: 'bi-cloud-download',
} as const;

export type AppIconName = (typeof APP_ICONS)[keyof typeof APP_ICONS];

/**
 * Closest built-in glyph for the iOS/Android builds. The website never reads
 * this table — it exists only so the native renderer has a valid glyph name.
 */
export const NATIVE_FALLBACK: Record<AppIconName, string> = {
  'bi-house-door': 'home',
  'bi-house-door-fill': 'home',
  'bi-list': 'menu',
  'bi-x-lg': 'close',
  'bi-search': 'search',
  'bi-download': 'download',
  'bi-file-earmark-text': 'document-text',
  'bi-ticket-perforated': 'ticket',
  'bi-calendar3': 'calendar',
  'bi-grid-3x3-gap': 'grid',
  'bi-list-ul': 'list',
  'bi-person': 'person',
  'bi-person-plus': 'person-add',
  'bi-bell': 'notifications',
  'bi-activity': 'pulse',
  'bi-speedometer2': 'speedometer',
  'bi-bar-chart': 'bar-chart',
  'bi-shield-check': 'shield-checkmark',
  'bi-box-arrow-right': 'log-out-outline',
  'bi-box-arrow-in-right': 'log-in',
  'bi-globe': 'globe',
  'bi-geo-alt': 'location',
  'bi-building': 'business',
  'bi-clock': 'time',
  'bi-megaphone': 'megaphone',
  'bi-people': 'people',
  'bi-check-circle': 'checkmark-circle',
  'bi-check2-all': 'checkmark-done',
  'bi-check-lg': 'checkmark',
  'bi-flag': 'flag',
  'bi-info-circle': 'information-circle',
  'bi-receipt': 'receipt',
  'bi-exclamation-triangle': 'warning',
  'bi-x-circle': 'alert-circle',
  'bi-inbox': 'file-tray',
  'bi-arrow-clockwise': 'refresh',
  'bi-arrow-repeat': 'refresh-circle',
  'bi-chevron-down': 'chevron-down',
  'bi-chevron-right': 'chevron-forward',
  'bi-chevron-left': 'chevron-back',
  'bi-arrow-right': 'arrow-forward',
  'bi-archive': 'archive',
  'bi-flower1': 'leaf',
  'bi-map': 'map',
  'bi-translate': 'language',
  'bi-display': 'desktop',
  'bi-eye': 'eye',
  'bi-phone': 'phone-portrait',
  'bi-pie-chart': 'pie-chart',
  'bi-clipboard': 'clipboard',
  'bi-sliders': 'options',
  'bi-funnel': 'filter',
  'bi-cloud-download': 'cloud-download',
};
